version: "3"
services:
    dtserver:
      build:
        context: ./Dynatrace-Server
        args:
          - DT_HOME=${DT_HOME}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - DT_SERVER_LICENSE_KEY_FILE_URL=${DT_SERVER_LICENSE_KEY_FILE_URL}
          - CUID=${CUID}
          - CGID=${CGID}
      container_name: "${DT_SERVER_NAME}"
      image: "dynatrace/server:7.0"
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_HOME
        - DT_SERVER_LICENSE_KEY_FILE_URL
        - APPMON_COLLECTOR_SERVER_SSL_PORT
      ports:
        # Browser to server ports NonSSL 8020 SSL 8021 (to start the Webstart Client)
        - "${APPMON_WEB_CLIENT_NONSSL_PORT:-8020}:8020"
        - "${APPMON_WEB_CLIENT_SSL_PORT:-8021}:8021"
        # 9911 AppMon Web
        - "${APPMON_WEB_SSL_PORT:-9911}:9911"
        # 8040  Non SSL Collector to server port for Web Base Agents (or direct agent to server)
        # 8041  SSL Collector to server port for Web Base Agents (or direct agent to server)
        - "${APPMON_ONEAGENT_NONSSL_SERVER_PORT:-8040}:8040"
        - "${APPMON_ONEAGENT_SSL_SERVER_PORT:-8041}:8041"
        # 2021 Client to Frontend Server - non SSL
        - "${APPMON_CLIENT_NONSSL_PORT:-2021}:2021"
        # 8023 Client to Frontend Server - encrypted via HTTP tunnel
        - "${APPMON_CLIENT_SSL_PORT:-8023}:8023"
        # 6699 Collector to Server SSL
        - "${APPMON_COLLECTOR_SERVER_SSL_PORT:-6699}:6699"
        # 9998 - Legacy Agent to server embedded Collector (default)
      volumes:
        - "${DT_SERVER_LOG_PATH_ON_HOST}:${DT_HOME}/log/server/dtserver"
      networks:
        - appmon
      user: "${CUID}:${CGID}"

    dtcollector:
      build:
        context: ./Dynatrace-Collector
        args:
          - DT_HOME=${DT_HOME}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - CUID=${CUID}
          - CGID=${CGID}
      container_name: "${DT_COLLECTOR_NAME}"
      image: "dynatrace/collector:7.0"
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_HOME
        - DT_SERVER_LICENSE_KEY_FILE_URL
        - DT_SERVER_NAME
        - APPMON_COLLECTOR_PORT
        - APPMON_ONEAGENT_NONSSL_PORT
        - APPMON_ONEAGENT_SSL_PORT
        - APPMON_COLLECTOR_SERVER_SSL_PORT
      ports:
        # 9998 - Legacy Agent to Collector
        - "${APPMON_COLLECTOR_PORT:-9998}:9998"
        # 8042 One Agent to Collector non SSL
        - "${APPMON_ONEAGENT_NONSSL_PORT:-8042}:8042"
        # 8043 One Agent to Collector SSL
        - "${APPMON_ONEAGENT_SSL_PORT:-8043}:8043"
      volumes:
        - "${DT_COLLECTOR_LOG_PATH_ON_HOST}:${DT_HOME}/log/collector/dtcollector"
      networks:
        - appmon
      user: "${CUID}:${CGID}"

    dtagent:
      build:
        context: ./Dynatrace-Agent
        args:
          - DT_HOME=${DT_HOME}
          - VERSION=${VERSION}
          - BUILD_VERSION=${BUILD_VERSION}
          - CUID=${CUID}
          - CGID=${CGID}
      container_name: "${DT_AGENT_NAME}"
      image: "dynatrace/agent:7.0"
      environment:
        - COMPOSE_PROJECT_NAME
        - DT_HOME
        - DT_AGENT_COLLECTOR="${DT_COLLECTOR_NAME}:9998"
        - AGENT_LIB32
        - AGENT_LIB64
        - NODE_AGENT_LIB32
        - NODE_AGENT_LIB64
        - WSAGENT_BIN64
        - WSAGENT_INI
      volumes:
        - ${DT_HOME}
        - ${DT_HOME}/agent/lib64
        - "${DT_AGENT_LOG_PATH_ON_HOST}:${DT_HOME}/log/agent"
      networks:
        - appmon
      user: "${CUID}:${CGID}"

networks:
    appmon:
        driver: bridge
